# PlatformIO pre-build script: embeds models/*.tflite as 16-byte-aligned C arrays.
# Runs automatically on `pio run`; regenerates src/model_data.cc only when a model changes.
import os

try:
    Import("env")  # noqa: F821  (provided by PlatformIO/SCons)
    PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
except NameError:  # plain `python gen_model_data.py`
    PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

MODELS = [
    ("g_model_compressed", "models/ids_compressed_int8.tflite"),
    ("g_model_baseline", "models/ids_baseline_fp32.tflite"),
]
OUT_CC = os.path.join(PROJECT_DIR, "src", "model_data.cc")
OUT_H = os.path.join(PROJECT_DIR, "include", "model_data.h")


def _needs_update():
    if not (os.path.exists(OUT_CC) and os.path.exists(OUT_H)):
        return True
    out_mtime = min(os.path.getmtime(OUT_CC), os.path.getmtime(OUT_H))
    return any(os.path.getmtime(os.path.join(PROJECT_DIR, p)) > out_mtime for _, p in MODELS)


def generate():
    header = ["// Auto-generated by gen_model_data.py - do not edit.", "#pragma once", ""]
    source = ['// Auto-generated by gen_model_data.py - do not edit.', '#include "model_data.h"', ""]
    for name, rel in MODELS:
        with open(os.path.join(PROJECT_DIR, rel), "rb") as f:
            data = f.read()
        header += [f"// {rel} ({len(data)} bytes)",
                   f"extern const unsigned char {name}[];",
                   f"extern const unsigned int {name}_len;", ""]
        source.append(f"alignas(16) const unsigned char {name}[] = {{")
        for i in range(0, len(data), 16):
            source.append("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
        source += ["};", f"const unsigned int {name}_len = {len(data)};", ""]
    with open(OUT_H, "w", newline="\n") as f:
        f.write("\n".join(header))
    with open(OUT_CC, "w", newline="\n") as f:
        f.write("\n".join(source))
    print(f"[gen_model_data] wrote {OUT_CC}")


if _needs_update():
    generate()
